[package]
name = "chain_indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
mongodb = "2.6.0"
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
serde = { version = "1", features = ["derive"] }
bson = "1.2"
warp = "0.3"